#=
Parametric structure generators, plot-geometry extraction, and model
utilities — absorbed from AsapToolkit (its original test suite, adapted).
Smoke tests (constructors run, models solve) plus sanity checks
(global equilibrium, displacement recovery, model↔network round trips).
=#

"Sum of all applied external forces [Fx, Fy, Fz] on a model."
function total_applied_gen(model::Model)
    F = zeros(3)
    for load in model.loads
        if load isa NodeForce
            F .+= Vector(load.value)
        elseif load isa DistributedLoad
            #uniform full-span loads (as generated by LineLoad)
            F .+= Vector(load.direction) .* (first(load.w) * length(load.element))
        end
    end
    return F
end

"Sum of reactions along global direction `i` (1 = X, 2 = Y, 3 = Z)."
reaction_sum_gen(model::Model, i::Integer) = sum(model.results.reactions[i:6:end])

"Test static global equilibrium in direction `i`."
function test_equilibrium_gen(model::Model, i::Integer)
    F = total_applied_gen(model)
    @test isapprox(reaction_sum_gen(model, i), -F[i]; rtol = 1e-8)
end

#a basic frame section (kN-m-ish units)
gen_mat = Material(200e6, 77e6, 80.0, 0.3)
gen_frame_section = Section(gen_mat, 1e-2, 1e-4, 5e-5, 1e-6)
gen_truss_section = Section(gen_mat, 1e-3)

@testset "Generation" begin

    @testset "Warren2D" begin
        gen = Warren2D(7, 1.5, 1.2, gen_truss_section)
        @test gen.model isa Model{Float64}
        @test !isnothing(gen.model.results)
        test_equilibrium_gen(gen.model, 2)

        #NOTE: the vector-input Warren2D method is not tested — it references
        #undefined variables (`dx`, `dy`) in its final line and was broken
        #before the v1.0 port.
    end

    @testset "Pratt2D" begin
        gen = Pratt2D(12.0, 6, 1.5, gen_truss_section)
        @test gen.model isa Model{Float64}
        test_equilibrium_gen(gen.model, 2)
    end

    @testset "BakerTruss" begin
        gen = BakerTruss(4, 1.0, 1.0, gen_truss_section)
        @test gen.model isa Model{Float64}
        test_equilibrium_gen(gen.model, 2)
    end

    @testset "TrussFrame" begin
        gen = TrussFrame(6, 1.0, 3, 1.0, gen_truss_section)
        @test gen.model isa Model{Float64}
        test_equilibrium_gen(gen.model, 2)
    end

    @testset "SpaceFrame" begin
        gen = SpaceFrame(4, 1.0, 4, 1.0, 1.0, gen_truss_section)
        @test gen.model isa Model{Float64}
        test_equilibrium_gen(gen.model, 3)

        #variable-depth variant: any callable surface(u, v) on [0,1]²
        gen2 = SpaceFrame(4, 1.0, 4, 1.0, 1.0,
            (u, v) -> 0.5 * sinpi(u) * sinpi(v), gen_truss_section)
        @test gen2.model isa Model{Float64}
        test_equilibrium_gen(gen2.model, 3)
    end

    @testset "SpaceFrameBeam" begin
        gen = SpaceFrameBeam(4, 1.0, 1.0, 1.0, gen_truss_section)
        @test gen.model isa Model{Float64}
        test_equilibrium_gen(gen.model, 3)
    end

    @testset "Frame" begin
        gen = Frame(2, 6.0, 2, 5.0, 2, 4.0, 2.0,
            gen_frame_section, gen_frame_section, gen_frame_section, gen_frame_section)
        @test gen.model isa Model{Float64}
        test_equilibrium_gen(gen.model, 3)

        #generated index sets are consistent
        n_nodes = length(gen.model.nodes)
        @test all(1 .<= gen.iExteriorXnodes .<= n_nodes)
        @test all(1 .<= gen.iExteriorYnodes .<= n_nodes)
    end

    @testset "GridFrame" begin
        gen = GridFrame(6.0, 4, 6.0, 4, gen_frame_section)
        @test gen.model isa Model{Float64}
        test_equilibrium_gen(gen.model, 3)
    end

    @testset "GridNetwork (FDM)" begin
        gen = GridNetwork(4, 6.0, 4, 6.0)
        @test gen.network isa Network
        @test gen.network.cache !== nothing
    end

    @testset "Ground structures" begin
        gs = XGroundStructure(4.0, 4, 4.0, 4)
        truss = to_truss(gs, gen_truss_section; load = [1.0, 0.0, 0.0])
        @test truss isa Model{Float64}
        test_equilibrium_gen(truss, 1)

        frame = to_frame(gs, gen_frame_section)
        @test frame isa Model{Float64}
        test_equilibrium_gen(frame, 3)
    end

    @testset "Geo" begin
        truss_gen = Pratt2D(12.0, 6, 1.5, gen_truss_section)
        geo = Geo(truss_gen.model)
        @test geo isa ModelGeo
        @test length(geo.nodes) == length(truss_gen.model.nodes)
        @test length(geo.lengths) == length(truss_gen.model.elements)

        tgeo = TrussGeo(truss_gen.model)
        @test tgeo isa TrussGeo
        @test length(tgeo.forces) == length(truss_gen.model.elements)
        @test tgeo.max_abs_force > 0

        frame_gen = GridFrame(6.0, 4, 6.0, 4, gen_frame_section)
        fgeo = Geo(frame_gen.model)
        @test fgeo isa ModelGeo
        @test fgeo.max_abs_My > 0

        ngeo = Geo(GridNetwork(4, 6.0, 4, 6.0).network)
        @test ngeo isa NetworkGeo
    end

    @testset "ElementDisplacements" begin
        #cantilever with tip load
        n1 = Node([0.0, 0.0, 0.0], :fixed)
        n2 = Node([2.0, 0.0, 0.0], :free, :tip)
        el = FrameElement(n1, n2, gen_frame_section)
        load = NodeForce(n2, [0.0, 0.0, -10.0])

        model = Model([n1, n2], [el], [load])
        solve!(model)

        ed = ElementDisplacements(el, model; resolution = 11)

        @test size(ed.uglobal) == (3, 11)
        @test ed.uglobal[:, 1] ≈ zeros(3) atol = 1e-12

        #sampled shape at t = 1 matches the tip nodal displacement
        utip = Vector(displacement(model.results, n2)[1:3])
        @test isapprox(ed.uglobal[:, end], utip; rtol = 1e-8)

        #base positions run along the element
        @test ed.basepositions[:, 1] ≈ Vector(n1.position)
        @test ed.basepositions[:, end] ≈ Vector(n2.position)

        #all-element sampling
        eds = displacements(model, 0.5)
        @test length(eds) == length(model.elements)

        #truss version: linear interpolation of end displacements
        truss_gen = Pratt2D(12.0, 6, 1.5, gen_truss_section)
        tel = truss_gen.model.elements[1]
        ted = ElementDisplacements(tel, truss_gen.model; resolution = 5)
        tu2 = Vector(displacement(truss_gen.model.results, tel.nodeEnd)[1:3])
        @test isapprox(ted.uglobal[:, end], tu2; rtol = 1e-8)
    end

    @testset "FDM translations" begin
        truss_gen = Pratt2D(12.0, 6, 1.5, gen_truss_section)
        network = to_network(truss_gen.model)
        @test network isa Network
        @test network.cache !== nothing
        @test length(network.elements) == length(truss_gen.model.elements)

        truss_back = to_truss(network, gen_truss_section)
        @test truss_back isa Model{Float64}
        @test !isnothing(truss_back.results)
    end

    @testset "Model utilities" begin
        gen = Pratt2D(12.0, 6, 1.5, gen_truss_section)
        Cel = element_connectivity(gen.model)
        n_el = length(gen.model.elements)
        @test size(Cel) == (n_el, n_el)
        @test Cel == Cel'

        m2 = Warren2D(7, 1.5, 1.2, gen_truss_section).model
        clear_supports!(m2)
        #every DOF is free (fixity `true` = free) and ids reset
        @test all(all(n.fixity) for n in m2.nodes)
        @test all(n.id == :free for n in m2.nodes)
    end

    @testset "Show methods" begin
        gen = Pratt2D(12.0, 6, 1.5, gen_truss_section)
        @test occursin("parametric structure generator", repr(MIME("text/plain"), gen))
        @test occursin("Model:", repr(MIME("text/plain"), gen))

        gs = XGroundStructure(4.0, 4, 4.0, 4)
        @test occursin("ground structure", repr(MIME("text/plain"), gs))

        geo = Geo(gen.model)
        @test occursin("plot-ready", repr(MIME("text/plain"), geo))

        n1 = Node([0.0, 0.0, 0.0], :fixed)
        n2 = Node([2.0, 0.0, 0.0], :free)
        el = FrameElement(n1, n2, gen_frame_section)
        m = Model([n1, n2], [el], [NodeForce(n2, [0.0, 0.0, -1.0])])
        solve!(m)
        ed = ElementDisplacements(el, m)
        @test occursin("displaced shape", repr(MIME("text/plain"), ed))
    end

end
