# Regenerates test/characterization/fixtures.jl by running the CURRENT Asap
# and pinning its exact numeric outputs. Run from the repo root:
#
#     julia --project=. test/characterization/generate_fixtures.jl
#
# Only regenerate deliberately: a diff in fixtures.jl is a behavior change.
# See docs/MODERNIZATION.md (Phase 0).

using Asap
using LinearAlgebra

include(joinpath(@__DIR__, "models.jl"))

fixtures = Dict{String,Any}()

solved_models = [
    "truss_2d" => char_truss_2d,
    "frame_2d" => char_frame_2d,
    "truss_3d" => char_truss_3d,
    "frame_3d" => char_frame_3d,
    "cantilever_tip" => char_cantilever_tip,
    "cantilever_midpoint" => char_cantilever_midpoint,
    ["portal_$r" => (() -> char_portal_frame(r)) for r in CHAR_RELEASES]...,
]

for (name, builder) in solved_models
    model = builder()
    solve!(model)
    fixtures["$name/u"] = model.u
    fixtures["$name/reactions"] = model.reactions
    fixtures["$name/compliance"] = model.compliance
    fixtures["$name/element_forces"] = [el.forces for el in model.elements]
end

# Fixed-end forces, local & global stiffness, and transformation per release
# on a skewed element — the oracles for the fixity-factor kernel (Phase 1)
# and the Gauss/Hermite FEF engine (Phase 2).
for r in CHAR_RELEASES
    model = char_fef_element(r)
    process!(model)
    el = model.elements[1]

    fixtures["fef_$r/R"] = el.R
    fixtures["fef_$r/LCS"] = el.LCS
    fixtures["fef_$r/length"] = el.length
    fixtures["fef_$r/local_K"] = Asap.local_K(el)
    fixtures["fef_$r/global_K"] = el.K
    fixtures["fef_$r/Q"] = el.Q

    for load in model.loads
        kind = load isa LineLoad ? "lineload" : "pointload"
        fixtures["fef_$r/q_local/$kind"] = Asap.q_local(load)
        fixtures["fef_$r/q/$kind"] = Asap.q(load)
    end
end

path = joinpath(@__DIR__, "fixtures.jl")
open(path, "w") do io
    println(io, "# AUTO-GENERATED by generate_fixtures.jl using Asap v",
        pkgversion(Asap), " on Julia v", VERSION, ".")
    println(io, "# Pins exact v0.2.x numerics — do not edit by hand; regenerate deliberately.")
    println(io, "FIXTURES = Dict{String,Any}(")
    for key in sort!(collect(keys(fixtures)))
        println(io, "    ", repr(key), " => ", repr(fixtures[key]), ",")
    end
    println(io, ")")
end

println("Wrote $(length(fixtures)) fixtures to $path")
