# Regenerates fixtures_toolkit.jl: AsapToolkit's InternalForces diagrams
# (P, My, Vy, Mz, Vz sampled along each element) on the canonical portal
# frames, pinned as oracles for the Phase 3 equilibrium force-recovery
# rewrite in Asap core. Run from the Asap repo root:
#
#     julia test/characterization/generate_toolkit_fixtures.jl
#
# Self-contained: activates a temp environment dev'ing the LOCAL Asap and
# AsapToolkit so the pinned values correspond to this working tree.
#
# AXIS-NAMING TRAP (do not "fix" here — pin as-is, translate in Phase 3):
# Toolkit's `.My` is built from Flocal[6] and pairs with Vy — it is the
# bending moment about the local *z* axis. Its `.Mz` is the moment about
# local y. The modern API renames: old.My -> new.Mz, old.Mz -> new.My,
# old.P -> new.N. Toolkit's Flocal also omits element.Q, so these diagrams
# are only trustworthy for the load types its formula catalog covers
# (LineLoad/PointLoad — which is what the portal models use).

using Pkg
Pkg.activate(; temp=true)
Pkg.develop([
    PackageSpec(path=joinpath(@__DIR__, "..", "..")),                      # local Asap
    PackageSpec(path=joinpath(@__DIR__, "..", "..", "..", "AsapToolkit")), # local AsapToolkit
])

using Asap, AsapToolkit

include(joinpath(@__DIR__, "models.jl"))

fixtures = Dict{String,Any}()
skipped = String[]

for r in CHAR_RELEASES
    model = char_portal_frame(r)
    solve!(model)

    for el in model.elements
        # beam is unique; disambiguate the two columns by index
        tag = "$(el.id)$(el.elementID)"
        # NOTE: the (element, model) constructor is dead code against Asap
        # 0.2.2 (reads nonexistent element.release / element.loadIDs), and
        # get_elemental_loads chokes on NodeLoads — pass element loads directly.
        elloads = Asap.ElementLoad[l for l in model.loads if l isa Asap.ElementLoad && l.element === el]
        f = try
            InternalForces(el, elloads; resolution=21)
        catch err
            # Toolkit's formula catalog is incomplete (e.g. no MPoint/VPoint
            # methods for Joist point loads) — skip and record the gap.
            msg = first(split(sprint(showerror, err, context=:compact => true), '\n'))
            push!(skipped, "portal_$r/$tag ($msg)")
            continue
        end
        fixtures["portal_$r/$tag/x"] = f.x
        fixtures["portal_$r/$tag/P"] = f.P
        fixtures["portal_$r/$tag/My"] = f.My
        fixtures["portal_$r/$tag/Vy"] = f.Vy
        fixtures["portal_$r/$tag/Mz"] = f.Mz
        fixtures["portal_$r/$tag/Vz"] = f.Vz
    end
end

path = joinpath(@__DIR__, "fixtures_toolkit.jl")
open(path, "w") do io
    println(io, "# AUTO-GENERATED by generate_toolkit_fixtures.jl using Asap v",
        pkgversion(Asap), " + AsapToolkit v", pkgversion(AsapToolkit),
        " on Julia v", VERSION, ".")
    println(io, "# Oracles for Phase 3 force recovery. NOTE the axis-naming trap:")
    println(io, "# Toolkit .My = moment about local z (pairs with Vy); .Mz = moment about local y.")
    for s in skipped
        println(io, "# SKIPPED (Toolkit formula catalog gap): ", s)
    end
    println(io, "TOOLKIT_FIXTURES = Dict{String,Any}(")
    for key in sort!(collect(keys(fixtures)))
        println(io, "    ", repr(key), " => ", repr(fixtures[key]), ",")
    end
    println(io, ")")
end

println("Wrote $(length(fixtures)) fixtures to $path")
